### ISSUE TITLE
DTRreplica01 Not registered with ELB

### ISSUE THREAD

**Issue by ahawkins** [aws-quickstart/quickstart-docker#10]
The `UserData` script for:
- `DTRreplica01`: https://github.com/aws-quickstart/quickstart-docker/blob/develop/templates/quickstart-docker.template#L1480, just verify.
- `DTRreplica02`: https://github.com/aws-quickstart/quickstart-docker/blob/develop/templates/quickstart-docker.template#L1676-L1680, verify, register with ELB
- `DTRreplica03`: https://github.com/aws-quickstart/quickstart-docker/blob/develop/templates/quickstart-docker.template#L1816-L1823

Why isn't `DTRreplica02` added to the ELB?

**Comment by nicolaka** [comment]
@ahawkins it should be added using https://github.com/aws-quickstart/quickstart-docker/blob/develop/templates/quickstart-docker.template#L1527

**Comment by ahawkins** [comment]
Does that also attach it to the ELB, if so then today I learned. If so
then that doesn't explain why the other 2 replicas require a specific
call to attach the ELB.


On Fri, Aug 12, 2016, at 02:58 AM, Nicola Kabar wrote:
> @ahawkins[1] it should be added using
> https://github.com/aws-quickstart/quickstart-docker/blob/develop/templates/quickstart-docker.template#L1527
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>


Links:

  1. https://github.com/ahawkins
  2. https://github.com/aws-quickstart/quickstart-docker/issues/10#issuecomment-239298536

**Comment by nicolaka** [comment]
@ahawkins not sure why is that happening. In my install it automatically registers all three with the ELB. 

<img width="1136" alt="screen shot 2016-08-12 at 11 35 52 am" src="https://cloud.githubusercontent.com/assets/11139046/17633217/07723a28-6081-11e6-9139-bacf498bd76d.png">

**Comment by nicolaka** [comment]
@ahawkins https://github.com/aws-quickstart/quickstart-docker/blob/develop/templates/quickstart-docker.template#L1864 should register it.

**Comment by bchav** [comment]
We needed to do this because DTR requires the replicas to join the cluster serially. Once this is no longer a requirement in DTR we can join them to the ELB using CFN directly instead of with a CLI call.
