### ISSUE TITLE
Cannot SSH into instances

### ISSUE THREAD

**Issue by ahawkins** [aws-quickstart/quickstart-docker#3]
I provided the key pair so SSH is possible. However it doesn't seem the network rules to allow it. This would be useful in debugging cases. Is this expected to work out of the box?

**Comment by bchav** [comment]
Hey @ahawkins, you're correct: you do not have direct SSH access to the instances. All instances are in a private subnet, so you'll need to launch an instance in one of the public subnets to use as a bastion host. 

We recommend using an SSH agent with your bastion host so you do not need to copy your SSH key around: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by ahawkins** [comment]
@bchav Ok, thanks for the info. That's helpful. I can automate that as well :)

**Comment by ahawkins** [comment]
From https://github.com/nicolaka/ddc-aws

> SSH: If you need to SSH into the cluster you need to edit the security group setting to allow TCP port 22. Additionally, since all the instances are not part of any public subnet, you need to launch a separate jumphost on the public subnet and use it to ssh into any of the EC2 instances.

IMO this template should update the security group and add the public subnet to outputs.

**Comment by nicolaka** [comment]
good feedback @ahawkins .

**Comment by nicolaka** [comment]
@ahawkins can you let us know if you're able to successfully deploy the stack?
