### ISSUE TITLE
InstanceType m4.large deploy fails

### ISSUE THREAD

**Issue by ahawkins** [aws-quickstart/quickstart-docker#4]
This fails because not every value listed in the allowed values for the instance type is listed in the `AWSInstanceType2Arch` mapping. It seems all the `m4.*` are unmapped.

**Comment by bchav** [comment]
Good callout. This was fixed in our original repo here: https://github.com/nicolaka/ddc-aws/pull/44

We'll open a PR against this repo, as well.

**Comment by ahawkins** [comment]
@bchav ah, so which repo is the source of truth for the template?

**Comment by bchav** [comment]
You should be able to use either. We've merged changes. This should be automated in the future. 

Closing this, feel free to re-open if you have questions.
