### ISSUE TITLE
Adding SSL certs unsupported

### ISSUE THREAD

**Issue by ahawkins** [aws-quickstart/quickstart-docker#6]
I see the CloudFormation template creates a bucket to keep this stuff, however a user cannot upload their own cert files. This blocks configuring proper SSL for UCP access. Also the appropriate `--san` parameters needs to be passed to the various `ucp` commands. Given the template does ask for the UCP subdomain the template should forward the information where appropriate.

**Comment by nicolaka** [comment]
@ahawkins next version of UCP would let you add them directly in UI for now please follow this doc on ALL controllers:

https://docs.docker.com/ucp/configuration/use-externally-signed-certs/
